# ---- JVM ----
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# ---- AndroidX ----
android.useAndroidX=true
android.nonTransitiveRClass=true

# ---- Kotlin ----
kotlin.code.style=official

# ---- 关闭 BuildConfig 生成（本工程未使用）----
android.defaults.buildfeatures.buildconfig=false
